[gdrive]
type = drive
scope = drive
token = {"access_token":"ya29.a0AdMD6EhnNTAfthDgR0yeG4VC3-F7LIsGsrOB_69sc2RfqSu7vC_MS6nkfVYfPtH_VVjokna6zpYrbTafdT7HN5ieT-w8lnY4cTMFH-2NXot-vy4VK0cq3QXa36E3-adOns8h79uJNJXBkjOj1b3FIcoOeo5iRt06eWgV6TbYWzjPX66NhpHXUt58m8FocFRfE1Jgr_MaCgYKAUwSARYSFQHGX2MiJTeIBuwb6V73tJ03PBgVKw0206","token_type":"Bearer","refresh_token":"1//05OpWFrxwmMIfCgYIARAAGAUSNwF-L9IrnjN7CehQES-tWHtpR2U2ObX9K99-XzYaL3F65oGB1hqsX23oDeWmkanPglAzCrcb94k","expiry":"2026-08-21T22:26:49.538947-05:00","expires_in":3599}
