// Infrastructure Barrel Export
export * from './storage/DexieStorageAdapter';
export * from './storage/InMemoryStorageAdapter';
export * from './storage/SupabaseStorageAdapter';
export * from './storage/LocalStorageEventStreamAdapter';
export * from './storage/WebKitPersistAdapter';
export * from './ServiceContainer';
export * from './data/providers.data';
export * from './data/rates.data';
export * from './data/archetypes.data';
export * from './ocr/SimulatedReceiptOCRAdapter';
export * from './export/JsonPdfExportAdapter';
export * from './security/Sha256LedgerChain';
export * from './crdt/LWWElementSet';
export * from './crdt/PNCounter';
